version: 2.1

jobs:

  test:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Install and start geckodriver
          command: |
            wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz &&
            tar -xvzf geckodriver* &&
            chmod +x geckodriver &&
            sudo mv geckodriver /usr/local/bin
      - run:
          name: Migrate django db and run tests
          command: |
            . venv/bin/activate
            python3 manage.py makemigrations
            python3 manage.py migrate
            pytest
            pytest functional_tests/functional_test_cohort_interface_feature.py
      - store_artifacts:
          path: test-reports/
          destination: concept_query

  # This job tests successful building docker image of the cohort definition tool
  # NOTE: To be used for testing docker images for deployment
  # build:
  #   docker:
  #     - image: cimg/python:3.9.8
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: Dockerbuild
  #         command: docker build --tag concept_query_test .


# Workflows can run multiple jobs in parallel.
# Currently, only the test workflow is active
workflows:
  version: 2
  test:
    jobs:
      - test
  # build:
  #   jobs:
  #     - build
  # build_and_test:
  #   jobs:
  #     - build
  #     - test