version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # - run:
      #     name: Install Docker Compose
      #     environment:
      #       COMPOSE_VERSION: '1.29.2'
      #     command: |
      #       curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
      #       chmod +x ~/docker-compose
      #       sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Dockerbuild
          command: docker build --tag concept_query_test . 
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Migrate django db and run tests
          command: |
            . venv/bin/activate
            python3 manage.py makemigrations
            python3 manage.py migrate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: concept_query