version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Dockerbuild
          command: docker build --tag concept_query_test . 
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

  test:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Migrate django db and run tests
          command: |
            . venv/bin/activate
            python3 manage.py makemigrations
            python3 manage.py migrate
            pytest
            # pytest functional_tests/functional_test_cohort_interface_feature.py
      - store_artifacts:
          path: test-reports/
          destination: concept_query

workflows:
  version: 2
  # build:
  #   jobs:
  #     - build
  test:
    jobs:
      - test
  # build_and_test:
  #   jobs:
  #     - build
  #     - test