# Generated by Django 3.2.8 on 2021-10-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('diagnosis', models.URLField()),
                ('gender', models.CharField(max_length=10)),
                ('isControl', models.BooleanField()),
                ('modality', models.CharField(max_length=30)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_prototype.datasetmetadata')),
            ],
        ),
    ]
