# Generated by Django 3.2.8 on 2021-10-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_prototype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryFieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_lower', models.FloatField()),
                ('age_upper', models.FloatField()),
                ('gender', models.CharField(max_length=3)),
                ('modality', models.CharField(max_length=30)),
                ('diagnosis', models.URLField()),
                ('isControl', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='DatasetMetadata',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
