# Generated by Django 3.2.8 on 2021-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_prototype', '0003_rename_iscontrol_queryfieldsmodel_is_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='gender',
            field=models.CharField(choices=[(1, 'M'), (2, 'F'), (3, 'All')], max_length=3),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='is_control',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'No'), (3, 'All')], max_length=3),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='modality',
            field=models.CharField(choices=[(1, 'FlowWeighted'), (2, 'DiffusionWeighted'), (3, 'T1Weighted'), (4, 'T2Weighted'), (5, 'All')], max_length=30),
        ),
    ]
