# Generated by Django 3.2.8 on 2021-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_prototype', '0005_auto_20211028_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryfieldsmodel',
            name='results',
            field=models.JSONField(default={'head': {}, 'results': {}}),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('All', 'All')], max_length=30),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='is_control',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('All', 'All')], max_length=30),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='modality',
            field=models.CharField(choices=[('FlowWeighted', 'FlowWeighted'), ('DiffusionWeighted', 'DiffusionWeighted'), ('T1Weighted', 'T1Weighted'), ('T2Weighted', 'T2Weighted'), ('All', 'All')], max_length=60),
        ),
    ]
