# Generated by Django 3.2.8 on 2021-11-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_prototype', '0009_alter_queryfieldsmodel_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='diagnosis',
            field=models.CharField(choices=[('http://purl.bioontology.org/ontology/SNOMEDCT/197480006', 'Anxiety disorder'), ('http://purl.bioontology.org/ontology/SNOMEDCT/126943008', 'Separation anxiety'), ('http://purl.bioontology.org/ontology/SNOMEDCT/25501002', 'Social phobia'), ('http://purl.bioontology.org/ontology/SNOMEDCT/127295002', 'Traumatic brain injury'), ('http://purl.bioontology.org/ontology/SNOMEDCT/300228004', 'Hearing problem'), ('http://purl.bioontology.org/ontology/SNOMEDCT/49049000', "Parkinson's disease"), ('http://purl.bioontology.org/ontology/SNOMEDCT/406506008', 'Attention deficit hyperactivity disorder'), ('http://purl.bioontology.org/ontology/SNOMEDCT/203082005', 'Fibromyalgia'), ('http://purl.bioontology.org/ontology/SNOMEDCT/397540003', 'Visual impairment'), ('http://purl.bioontology.org/ontology/SNOMEDCT/37796009', 'Migraine'), ('http://purl.bioontology.org/ontology/SNOMEDCT/712823008', 'Acute depression'), ('http://purl.bioontology.org/ontology/SNOMEDCT/77176002', 'Smoker'), ('http://purl.bioontology.org/ontology/SNOMEDCT/49601007', 'Disorder of cardiovascular system'), ('http://purl.bioontology.org/ontology/SNOMEDCT/74732009', 'Mental disorder'), ('http://purl.bioontology.org/ontology/SNOMEDCT/110030002', 'Concussion injury of brain'), ('http://purl.bioontology.org/ontology/SNOMEDCT/48694002', 'Anxiety'), ('http://purl.bioontology.org/ontology/SNOMEDCT/35919005', 'Autism spectrum disorder'), ('http://purl.bioontology.org/ontology/SNOMEDCT/59770006', 'Dyslexia'), ('http://purl.bioontology.org/ontology/SNOMEDCT/268738002', 'Specific spelling disorder'), ('http://purl.bioontology.org/ontology/SNOMEDCT/58214004', 'Schizophrenia'), ('http://purl.bioontology.org/ontology/SNOMEDCT/20010003', 'Borderline personality disorder'), (None, 'All')], max_length=200),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), (None, 'All')], max_length=200),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='is_control',
            field=models.CharField(choices=[('http://purl.org/nidash/nidm#Control', 'Control'), (None, 'All')], max_length=200),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='modality',
            field=models.CharField(choices=[('http://purl.org/nidash/nidm#FlowWeighted', 'Flow weighted'), ('http://purl.org/nidash/nidm#T1Weighted', 'T1 weighted'), ('http://purl.org/nidash/nidm#DiffusionWeighted', 'Diffusion weighted'), ('http://purl.org/nidash/nidm#T2Weighted', 'T2 weighted'), (None, 'All')], max_length=200),
        ),
    ]
