# Generated by Django 3.2.9 on 2021-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_prototype', '0010_auto_20211103_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='age_lower',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='queryfieldsmodel',
            name='age_upper',
            field=models.FloatField(null=True),
        ),
    ]
